import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Badge } from "@/components/ui/badge";
import SidebarApp from "@/app/(app)/sidebar-app";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f4f7fc]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <div className="lg:hidden flex flex-col items-center justify-center h-screen">
            <Badge className="bg-primary">Mobile currently unavailable</Badge>
            <div>Please open this page on desktop</div>
          </div>
          <div
            className={
              "hidden lg:flex flex-col h-screen w-full md:flex-row dark:bg-[#171717] overflow-hidden"
            }
          >
            <SidebarApp />
            <div className="w-full p-8 overflow-y-auto scrollbar-default  dark:scrollbar-dark  ">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
